### ISSUE TITLE
탭 빌드 후 사용하려 했더니 플러그인 오류가 발생합니다

### ISSUE THREAD

**Issue by 2T-ae** [noonmaru/tap#11]
Could not load 'plugins\tap-2.8.8.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more
[23:14:51 ERROR]: Could not load 'plugins\parkour-maker-0.3.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency Tap. Please download and install Tap to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

파쿠르 메이커를 실행하기 위해선 tap도 필요한데 사용이 안되네요... 버전은 1.16.1입니다

**Comment by noonmaru** [comment]
의존성 라이브러리 추가를 위해서 :distJar 태스크로 빌드하셔야합니다.

그리고 직접 빌드할 필요없이 release란에 배포버전이 있습니다.

**Comment by 2T-ae** [comment]
parkourmaker는 그냥 빌드하면 되나요?

**Comment by 2T-ae** [comment]
감사합니다 해결했습니다
