### ISSUE TITLE
Tap 플러그인을 서버에 넣고 서버를 열던 중 일어난 오류

### ISSUE THREAD

**Issue by jini5012** [noonmaru/tap#14]
제가 paper 서버를 열다가 오류가 났는데 오류로그를 알려 드릴게요
[15:15:56 ERROR]: Could not load 'plugins\tap-3.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.16.3.jar:git-Paper-191]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.3.jar:git-Paper-191]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:387) ~[patched_1.16.3.jar:git-Paper-191]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.3.jar:git-Paper-191]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-191]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-191]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml

이거를 어떻게 해결을 해야 하나요?

**Comment by ghost** [comment]
@jini5012 이 라이브러리는 3.0.0버전부터 플러그인이 아니므로 ShadowJar로 FatJar으로 만들어서 사용하셔야 합니다.

**Comment by ghost** [comment]
@jini5012 그리고 이제 plugins폴더에 Tap를 넣으시면 안됩니다.

**Comment by Apple6050** [comment]
이제 Tap가 필요한 플러그인 안에 Tap가 포함되어있기 때문에 Tap 라이브러리를 plugins에 넣으시면 안됩니다. @jini5012

**Comment by Apple6050** [comment]
@jini5012 3.0.0 릴리즈를 보시면 플러그인 지원 종료라는 내용를 보셨을겁니다

**Comment by jini5012** [comment]
> @jini5012 이 라이브러리는 3.0.0버전부터 플러그인이 아니므로 ShadowJar로 FatJar으로 만들어서 사용하셔야 합니다.

ShadowJar로 FatJar를 어떻게 만드나요?

**Comment by ghost** [comment]
@jini5012 간략하게 말하자면 이제 Tap를 빌드하지 않아도 됩니다.

**Comment by ghost** [comment]
https://github.com/johnrengelman/shadow 을 이용해서 FatJar을 만드는 것입니다.

**Comment by jini5012** [comment]
이 링크를 통해서 어쩌라는거죠? 제가 초보라서 모르는 게 많거든요.제성합니다.
ㅠㅠ

**Comment by patrick-choe** [comment]
> 이 링크를 통해서 어쩌라는거죠? 제가 초보라서 모르는 게 많거든요.제성합니다.
> ㅠㅠ

`>=3.0.0` 은 직접 빌드가 전혀 필요 없습니다. Shadow (FatJar Plugin) 역시 직접 Tap Library를 사용한 Bukkit 개발을 하지 않는다면 수행할 필요가 없습니다. 혹시 Shadow 사용법을 확인하고 싶으시다면 shadow plugin 레포지토리의 README, 혹은 Noonmaru님을 포함한 다른 개발자 분들의 사용 예시를 보면 되겠습니다.

**Comment by patrick-choe** [comment]
#13 noonmaru님께서 남겨두신 comment 확인하세요

**Comment by jini5012** [comment]
아니 지금 코딩 천재들이 하는 말을 1도 못알아듯겠어

**Comment by ilsubyeega** [comment]
Tap은 제가 기억하기로는 이제는 Plugin 이 아닌 라이브러리화가 되어있을 겁니다. 
ShadowJar 즉 FatJar는 본인이 제작한 플러그인 속에 Tap과 같은 라이브러리를 넣는 것으로, 직접 플러그인을 추가할 이유가 없어집니다.

만약 플러그인 개발자이시면: 혹시 본인이 Tap 라이브러리를 사용 중이신 플러그인은 gradle, maven, 또는 IDE 에서 직접 컴파일하시나요?

만약 kotlin-gradle-plugin 과 함께 gradle을 사용 중이시다면아래 #13 에서의 댓글 중 [이 주소](https://github.com/noonmaru/tap-sample-plugin/blob/master/build.gradle.kts)로 들어가지면 build.gradle.kts 파일이 있습니다. 본인의 플러그인이 gradle를 사용 중이라면 해당 파일로 덮어쓰기 하시는걸 권장합니다.

추가로 만약 Tap "플러그인"을 요구되는 플러그인이 있다면, 해당 개발자에게 최신 버전으로 업데이트를 해달라고 요청해보셔야 할 듯 합니다.

**Comment by minejango2** [comment]
그럼 플러그인 만든 사람이 아니면 사용해야할 플러그인의 소스코드를 다운받아서 tap과 연결되게 한 뒤 다시 빌드해야 하는건가요?

**Comment by jini5012** [comment]
> 그럼 플러그인 만든 사람이 아니면 사용해야할 플러그인의 소스코드를 다운받아서 tap과 연결되게 한 뒤 다시 빌드해야 하는건가요?

아마도 그렇게 하라는 것 같네요
